package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"
	"mantra_API/graphql/model"
	"mantra_API/models"
	"mantra_API/services"
	"strconv"
	"time"
)

// CreateMember is the resolver for the createMember field.
func (r *mutationResolver) CreateMember(ctx context.Context, input model.CreateMemberInput) (*model.Member, error) {
	svc := services.NewMemberService(r.DB)

	// 從 context 取得使用者 ID（如果沒有則使用 0 表示系統建立）
	creatorId := getUserIDFromContext(ctx)

	member, err := svc.CreateMember(input.Name, input.Email, input.Password, creatorId)
	if err != nil {
		return nil, err
	}

	return dbToModel(*member), nil
}

// UpdateMember is the resolver for the updateMember field.
func (r *mutationResolver) UpdateMember(ctx context.Context, id string, input model.UpdateMemberInput) (*model.Member, error) {
	svc := services.NewMemberService(r.DB)

	memberID, err := strconv.ParseUint(id, 10, 32)
	if err != nil {
		return nil, fmt.Errorf("無效的會員 ID")
	}

	// 從 context 取得使用者 ID
	modifierId := getUserIDFromContext(ctx)

	member, err := svc.UpdateMember(uint(memberID), input.Name, input.Email, modifierId)
	if err != nil {
		return nil, err
	}

	return dbToModel(*member), nil
}

// DeleteMember is the resolver for the deleteMember field.
func (r *mutationResolver) DeleteMember(ctx context.Context, id string) (bool, error) {
	svc := services.NewMemberService(r.DB)

	memberID, err := strconv.ParseUint(id, 10, 32)
	if err != nil {
		return false, fmt.Errorf("無效的會員 ID")
	}

	// 從 context 取得使用者 ID
	deleterId := getUserIDFromContext(ctx)

	if err := svc.DeleteMember(uint(memberID), deleterId); err != nil {
		return false, err
	}

	return true, nil
}

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input model.CreateProductInput) (*model.Product, error) {
	if r.DB == nil {
		return nil, fmt.Errorf("database connection not configured")
	}

	creatorID := getUserIDFromContext(ctx)

	product := models.Product{
		ProductName:        input.ProductName,
		ProductPrice:       input.ProductPrice,
		ProductDescription: ptrToString(input.ProductDescription),
		ProductImage:       ptrToString(input.ProductImage),
		ProductStock:       input.ProductStock,
		Base: models.Base{
			CreatorId: creatorID,
		},
	}

	if err := r.DB.Create(&product).Error; err != nil {
		return nil, err
	}

	return productDBToModel(product), nil
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, id string, input model.UpdateProductInput) (*model.Product, error) {
	if r.DB == nil {
		return nil, fmt.Errorf("database connection not configured")
	}

	productID, err := strconv.ParseUint(id, 10, 32)
	if err != nil {
		return nil, fmt.Errorf("invalid product ID")
	}

	var product models.Product
	if err := r.DB.Where("is_deleted = ?", false).First(&product, productID).Error; err != nil {
		return nil, fmt.Errorf("product not found")
	}

	modifierID := getUserIDFromContext(ctx)
	product.LastModifierId = modifierID

	updates := make(map[string]interface{})
	if input.ProductName != nil {
		updates["product_name"] = *input.ProductName
	}
	if input.ProductPrice != nil {
		updates["product_price"] = *input.ProductPrice
	}
	if input.ProductDescription != nil {
		updates["product_description"] = *input.ProductDescription
	}
	if input.ProductImage != nil {
		updates["product_image"] = *input.ProductImage
	}
	if input.ProductStock != nil {
		updates["product_stock"] = *input.ProductStock
	}
	updates["last_modifier_id"] = modifierID

	if err := r.DB.Model(&product).Updates(updates).Error; err != nil {
		return nil, err
	}

	// Reload product
	if err := r.DB.First(&product, productID).Error; err != nil {
		return nil, err
	}

	return productDBToModel(product), nil
}

// DeleteProduct is the resolver for the deleteProduct field.
func (r *mutationResolver) DeleteProduct(ctx context.Context, id string) (bool, error) {
	if r.DB == nil {
		return false, fmt.Errorf("database connection not configured")
	}

	productID, err := strconv.ParseUint(id, 10, 32)
	if err != nil {
		return false, fmt.Errorf("invalid product ID")
	}

	var product models.Product
	if err := r.DB.Where("is_deleted = ?", false).First(&product, productID).Error; err != nil {
		return false, fmt.Errorf("product not found")
	}

	if err := r.DB.Model(&product).Updates(map[string]interface{}{"is_deleted": true}).Error; err != nil {
		return false, err
	}

	return true, nil
}

// CreateMantra is the resolver for the createMantra field.
func (r *mutationResolver) CreateMantra(ctx context.Context, input model.CreateMantraInput) (*model.Mantra, error) {
	svc := services.NewMantraService(r.DB)
	creatorID := getUserIDFromContext(ctx)

	mantra, err := svc.CreateMantra(input.Content, ptrToString(input.Description), creatorID)
	if err != nil {
		return nil, err
	}

	return mantraDBToModel(*mantra), nil
}

// UpdateMantra is the resolver for the updateMantra field.
func (r *mutationResolver) UpdateMantra(ctx context.Context, id string, input model.UpdateMantraInput) (*model.Mantra, error) {
	svc := services.NewMantraService(r.DB)
	mantraID, err := parseUintID(id)
	if err != nil {
		return nil, err
	}

	updates := map[string]interface{}{}
	if input.Content != nil {
		updates["content"] = *input.Content
	}
	if input.Description != nil {
		updates["description"] = *input.Description
	}

	modifierID := getUserIDFromContext(ctx)
	mantra, err := svc.UpdateMantra(mantraID, updates, modifierID)
	if err != nil {
		return nil, err
	}

	return mantraDBToModel(*mantra), nil
}

// DeleteMantra is the resolver for the deleteMantra field.
func (r *mutationResolver) DeleteMantra(ctx context.Context, id string) (bool, error) {
	svc := services.NewMantraService(r.DB)
	mantraID, err := parseUintID(id)
	if err != nil {
		return false, err
	}

	deleterID := getUserIDFromContext(ctx)
	if err := svc.DeleteMantra(mantraID, deleterID); err != nil {
		return false, err
	}

	return true, nil
}

// CreateMantraRecord is the resolver for the createMantraRecord field.
func (r *mutationResolver) CreateMantraRecord(ctx context.Context, input model.CreateMantraRecordInput) (*model.MantraRecord, error) {
	svc := services.NewMantraRecordService(r.DB)
	mantraID, err := parseUintID(input.MantraID)
	if err != nil {
		return nil, err
	}

	saidAt, err := parseOptionalTime(input.SaidAt)
	if err != nil {
		return nil, err
	}

	creatorID := getUserIDFromContext(ctx)
	record, err := svc.CreateMantraRecord(mantraID, ptrToString(input.Location), saidAt, creatorID)
	if err != nil {
		return nil, err
	}

	return mantraRecordDBToModel(*record), nil
}

// DeleteMantraRecord is the resolver for the deleteMantraRecord field.
func (r *mutationResolver) DeleteMantraRecord(ctx context.Context, id string) (bool, error) {
	svc := services.NewMantraRecordService(r.DB)
	recordID, err := parseUintID(id)
	if err != nil {
		return false, err
	}

	deleterID := getUserIDFromContext(ctx)
	if err := svc.DeleteMantraRecord(recordID, deleterID); err != nil {
		return false, err
	}

	return true, nil
}

// CreateQuoteRecord is the resolver for the createQuoteRecord field.
func (r *mutationResolver) CreateQuoteRecord(ctx context.Context, input model.CreateQuoteRecordInput) (*model.QuoteRecord, error) {
	svc := services.NewQuoteRecordService(r.DB)
	creatorID := getUserIDFromContext(ctx)

	saidAtParsed, err := parseOptionalTime(input.SaidAt)
	if err != nil {
		return nil, err
	}

	saidAt := time.Now()
	if saidAtParsed != nil {
		saidAt = *saidAtParsed
	}

	record, err := svc.CreateQuoteRecord(input.JbName, input.Quote, saidAt, creatorID)
	if err != nil {
		return nil, err
	}

	return quoteRecordDBToModel(*record), nil
}

// UpdateQuoteRecord is the resolver for the updateQuoteRecord field.
func (r *mutationResolver) UpdateQuoteRecord(ctx context.Context, id string, input model.UpdateQuoteRecordInput) (*model.QuoteRecord, error) {
	svc := services.NewQuoteRecordService(r.DB)
	recordID, err := parseUintID(id)
	if err != nil {
		return nil, err
	}

	updates := map[string]interface{}{}
	if input.JbName != nil {
		updates["jb_name"] = *input.JbName
	}
	if input.Quote != nil {
		updates["quote"] = *input.Quote
	}
	if input.SaidAt != nil {
		t, parseErr := parseOptionalTime(input.SaidAt)
		if parseErr != nil {
			return nil, parseErr
		}
		if t != nil {
			updates["said_at"] = *t
		}
	}

	modifierID := getUserIDFromContext(ctx)
	record, err := svc.UpdateQuoteRecord(recordID, updates, modifierID)
	if err != nil {
		return nil, err
	}

	return quoteRecordDBToModel(*record), nil
}

// DeleteQuoteRecord is the resolver for the deleteQuoteRecord field.
func (r *mutationResolver) DeleteQuoteRecord(ctx context.Context, id string) (bool, error) {
	svc := services.NewQuoteRecordService(r.DB)
	recordID, err := parseUintID(id)
	if err != nil {
		return false, err
	}

	deleterID := getUserIDFromContext(ctx)
	if err := svc.DeleteQuoteRecord(recordID, deleterID); err != nil {
		return false, err
	}

	return true, nil
}

// CreateMessageBoard is the resolver for the createMessageBoard field.
func (r *mutationResolver) CreateMessageBoard(ctx context.Context, input model.CreateMessageBoardInput) (*model.MessageBoard, error) {
	svc := services.NewMessageBoardService(r.DB)
	quoteRecordID, err := parseUintID(input.QuoteRecordID)
	if err != nil {
		return nil, err
	}

	creatorID := getUserIDFromContext(ctx)
	message, err := svc.CreateMessage(input.Message, quoteRecordID, creatorID)
	if err != nil {
		return nil, err
	}

	return messageBoardDBToModel(*message), nil
}

// EditMessageBoard is the resolver for the editMessageBoard field.
func (r *mutationResolver) EditMessageBoard(ctx context.Context, id string, input model.EditMessageBoardInput) (*model.MessageBoard, error) {
	svc := services.NewMessageBoardService(r.DB)
	messageID, err := parseUintID(id)
	if err != nil {
		return nil, err
	}

	modifierID := getUserIDFromContext(ctx)
	message, err := svc.EditMessage(messageID, input.Message, modifierID)
	if err != nil {
		return nil, err
	}

	return messageBoardDBToModel(*message), nil
}

// DeleteMessageBoard is the resolver for the deleteMessageBoard field.
func (r *mutationResolver) DeleteMessageBoard(ctx context.Context, id string) (bool, error) {
	svc := services.NewMessageBoardService(r.DB)
	messageID, err := parseUintID(id)
	if err != nil {
		return false, err
	}

	deleterID := getUserIDFromContext(ctx)
	if err := svc.DeleteMessage(messageID, deleterID); err != nil {
		return false, err
	}

	return true, nil
}

// Member is the resolver for the member field.
func (r *queryResolver) Member(ctx context.Context, id string) (*model.Member, error) {
	if r.DB == nil {
		return nil, nil
	}
	var m models.Member
	if err := r.DB.First(&m, id).Error; err != nil {
		return nil, nil
	}
	return dbToModel(m), nil
}

// Members is the resolver for the members field.
func (r *queryResolver) Members(ctx context.Context, limit *int) ([]*model.Member, error) {
	if r.DB == nil {
		return []*model.Member{}, nil
	}
	lim := 50
	if limit != nil && *limit > 0 {
		lim = *limit
	}
	var rows []models.Member
	if err := r.DB.Select("id", "name", "email", "created_at", "updated_at").Limit(lim).Find(&rows).Error; err != nil {
		return nil, err
	}
	out := make([]*model.Member, len(rows))
	for i, m := range rows {
		out[i] = dbToModel(m)
	}
	return out, nil
}

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, id string) (*model.Product, error) {
	if r.DB == nil {
		return nil, nil
	}

	var product models.Product
	if err := r.DB.Where("is_deleted = ?", false).First(&product, id).Error; err != nil {
		return nil, nil
	}

	return productDBToModel(product), nil
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context, limit *int, offset *int) (*model.ProductsResponse, error) {
	if r.DB == nil {
		return &model.ProductsResponse{
			Products: []*model.Product{},
			Total:    0,
			Limit:    0,
			Offset:   0,
		}, nil
	}

	lim := 50
	if limit != nil && *limit > 0 {
		if *limit > 100 {
			lim = 100
		} else {
			lim = *limit
		}
	}

	off := 0
	if offset != nil && *offset >= 0 {
		off = *offset
	}

	var products []models.Product
	var total int64

	// Get total count
	if err := r.DB.Model(&models.Product{}).Where("is_deleted = ?", false).Count(&total).Error; err != nil {
		return nil, err
	}

	// Get products
	if err := r.DB.Where("is_deleted = ?", false).
		Order("sort ASC, id DESC").
		Limit(lim).
		Offset(off).
		Find(&products).Error; err != nil {
		return nil, err
	}

	out := make([]*model.Product, len(products))
	for i, p := range products {
		out[i] = productDBToModel(p)
	}

	return &model.ProductsResponse{
		Products: out,
		Total:    int(total),
		Limit:    lim,
		Offset:   off,
	}, nil
}

// Mantra is the resolver for the mantra field.
func (r *queryResolver) Mantra(ctx context.Context, id string) (*model.Mantra, error) {
	svc := services.NewMantraService(r.DB)
	mantraID, err := parseUintID(id)
	if err != nil {
		return nil, err
	}

	mantra, err := svc.GetMantraByID(mantraID)
	if err != nil {
		return nil, nil
	}

	return mantraDBToModel(*mantra), nil
}

// Mantras is the resolver for the mantras field.
func (r *queryResolver) Mantras(ctx context.Context, limit *int, offset *int) (*model.MantrasResponse, error) {
	svc := services.NewMantraService(r.DB)
	lim, off := normalizeLimitOffset(limit, offset)

	mantras, total, err := svc.GetMantras(lim, off)
	if err != nil {
		return nil, err
	}

	out := make([]*model.Mantra, len(mantras))
	for i, m := range mantras {
		out[i] = mantraDBToModel(m)
	}

	return &model.MantrasResponse{
		Mantras: out,
		Total:   int(total),
		Limit:   lim,
		Offset:  off,
	}, nil
}

// MantraRecord is the resolver for the mantraRecord field.
func (r *queryResolver) MantraRecord(ctx context.Context, id string) (*model.MantraRecord, error) {
	svc := services.NewMantraRecordService(r.DB)
	recordID, err := parseUintID(id)
	if err != nil {
		return nil, err
	}

	record, err := svc.GetMantraRecordByID(recordID)
	if err != nil {
		return nil, nil
	}

	return mantraRecordDBToModel(*record), nil
}

// MantraRecords is the resolver for the mantraRecords field.
func (r *queryResolver) MantraRecords(ctx context.Context, mantraID *string, limit *int, offset *int) (*model.MantraRecordsResponse, error) {
	svc := services.NewMantraRecordService(r.DB)
	lim, off := normalizeLimitOffset(limit, offset)

	filterMantraID := uint(0)
	if mantraID != nil && *mantraID != "" {
		parsed, err := parseUintID(*mantraID)
		if err != nil {
			return nil, err
		}
		filterMantraID = parsed
	}

	records, total, err := svc.GetMantraRecords(filterMantraID, lim, off)
	if err != nil {
		return nil, err
	}

	out := make([]*model.MantraRecord, len(records))
	for i, record := range records {
		out[i] = mantraRecordDBToModel(record)
	}

	return &model.MantraRecordsResponse{
		Records: out,
		Total:   int(total),
		Limit:   lim,
		Offset:  off,
	}, nil
}

// MantraDailyStats is the resolver for the mantraDailyStats field.
func (r *queryResolver) MantraDailyStats(ctx context.Context, mantraID string, days int) ([]*model.MantraDailyStat, error) {
	svc := services.NewMantraRecordService(r.DB)
	parsedMantraID, err := parseUintID(mantraID)
	if err != nil {
		return nil, err
	}

	stats, err := svc.GetDailyStats(parsedMantraID, days)
	if err != nil {
		return nil, err
	}

	out := make([]*model.MantraDailyStat, len(stats))
	for i, stat := range stats {
		out[i] = mantraDailyStatDBToModel(stat)
	}

	return out, nil
}

// QuoteRecord is the resolver for the quoteRecord field.
func (r *queryResolver) QuoteRecord(ctx context.Context, id string) (*model.QuoteRecord, error) {
	svc := services.NewQuoteRecordService(r.DB)
	recordID, err := parseUintID(id)
	if err != nil {
		return nil, err
	}

	record, err := svc.GetQuoteRecordByID(recordID)
	if err != nil {
		return nil, nil
	}

	return quoteRecordDBToModel(*record), nil
}

// QuoteRecords is the resolver for the quoteRecords field.
func (r *queryResolver) QuoteRecords(ctx context.Context, limit *int, offset *int) (*model.QuoteRecordsResponse, error) {
	svc := services.NewQuoteRecordService(r.DB)
	lim, off := normalizeLimitOffset(limit, offset)

	records, total, err := svc.GetQuoteRecords(lim, off)
	if err != nil {
		return nil, err
	}

	out := make([]*model.QuoteRecord, len(records))
	for i, record := range records {
		out[i] = quoteRecordDBToModel(record)
	}

	return &model.QuoteRecordsResponse{
		Records: out,
		Total:   int(total),
		Limit:   lim,
		Offset:  off,
	}, nil
}

// MessageBoard is the resolver for the messageBoard field.
func (r *queryResolver) MessageBoard(ctx context.Context, id string) (*model.MessageBoard, error) {
	svc := services.NewMessageBoardService(r.DB)
	messageID, err := parseUintID(id)
	if err != nil {
		return nil, err
	}

	message, err := svc.GetMessageByID(messageID)
	if err != nil {
		return nil, nil
	}

	return messageBoardDBToModel(*message), nil
}

// MessageBoards is the resolver for the messageBoards field.
func (r *queryResolver) MessageBoards(ctx context.Context, quoteRecordID string, limit *int, offset *int) (*model.MessageBoardsResponse, error) {
	svc := services.NewMessageBoardService(r.DB)
	parsedQuoteRecordID, err := parseUintID(quoteRecordID)
	if err != nil {
		return nil, err
	}

	lim, off := normalizeLimitOffset(limit, offset)
	messages, total, err := svc.GetMessagesByQuoteRecord(parsedQuoteRecordID, lim, off)
	if err != nil {
		return nil, err
	}

	out := make([]*model.MessageBoard, len(messages))
	for i, message := range messages {
		out[i] = messageBoardDBToModel(message)
	}

	return &model.MessageBoardsResponse{
		Messages: out,
		Total:    int(total),
		Limit:    lim,
		Offset:   off,
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
